apiVersion: apps/v1
kind: Deployment
metadata:
  name: prafulcloud
  labels:
    app: nginx
spec:
  replicas: 4
  strategy:
     type: RollingUpdate
     rollingUpdate:
       maxSurge: 0
       maxUnavailable: 2
  selector:
    matchLabels:
      app: nginx
  template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:1.12.1
          ports:
            - containerPort: 80





