apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: prafulcloud
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: team
        operator: In
        values:
          - dev
          - prod
          - test
    team: dev
  template:
    metadata:
      name: prafulcloud
      labels:
        team: dev
    spec:
      containers:
        - name: prafulcloud
          image: nginx:1.9.1
          ports:
            - containerPort: 80
