apiVersion: v1
kind: ReplicationController
metadata:
  name: web
spec:
  replicas: 3
  selector:
    team: dev
  template:
    metadata:
      name: web
      labels:
        team: dev
    spec:
      containers:
        - name: web
          image: nginx:1.7.1
          ports:
            - containerPort: 80
